# 문제 1

In [3]:
# 다음과 같은 numpy array가 있을 때 출력 결과가 나올 수 있도록 빈칸을 채우시오.
import numpy as np
array = np.array([[1,2,3], [3,4,5], [5,6,7], [10,20,30]])

print(array[1:2, 2:3])
print()
print(array[3, :])
print()
print(array[2:4, :])
print()
print(array[1:3, ::2])
print()
print(array[2:3:])

[[5]]

[10 20 30]

[[ 5  6  7]
 [10 20 30]]

[[3 5]
 [5 7]]

[[5 6 7]]


# 문제 2

In [4]:
# 다음과 같은 numpy array가 있을 때 Boolean indexing을 활용하여 출력 결과가 나올 수 있도록 빈칸을 채우시오.
import numpy as np
an_array = np.array([[11,12], [21,22], [31,32]])
an_array[(an_array > 20) & (an_array < 30)]

array([21, 22])

# 문제 3

In [7]:
# 3 - 1)결과 1과 같이 0부터 14까지 15개의 요소를 갖는 (3, 5)크기의 numpy array를 array라는 변수에 저장하여 출력하는 코드를 작성하고 결과를 출력하시오.
import numpy as np
array1 = np.array(range(15))
array2 = array1.reshape(3, 5)
array1[array2]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
# 3 – 2)위 3-1에서 작성한 array와 boolean indexing 이용하여 결과 2와 같이 3으로 나눠떨어지는 수에 50을 더하는 코드를 작성하고 결과를 출력하시오.
import numpy as np
array3 = np.array(range(15))
array4 = array3.reshape(3, 5)
array4[array4 % 3 == 0] += 50
np.array(array4)

array([[50,  1,  2, 53,  4],
       [ 5, 56,  7,  8, 59],
       [10, 11, 62, 13, 14]])