# 문제 1

In [7]:
# 코드1과 같이 (3,4,2) shape의 numpy array가 있다.
# 문제1-1) 결과 1과 같은 출력 결과가 나오도록 빈칸을 채우시오.
import numpy as np
array = np.arange(24).reshape(3, 4, 2)
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [8]:
# 문제1-2) 결과 2와 같은 출력 결과가 나오도록 빈칸을 채우시오.
s0 = array.sum(axis = 0)
s1 = array.sum(axis = 2)
s2 = array.sum(axis = 1)

print(s0)
print()
print(s1)
print()
print()
print(s2)

[[24 27]
 [30 33]
 [36 39]
 [42 45]]

[[ 1  5  9 13]
 [17 21 25 29]
 [33 37 41 45]]


[[12 16]
 [44 48]
 [76 80]]
